### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fosaal** [sailro/EscapeFromTarkov-Trainer#100]
Is this trainer meant for offline tarkov mode, or is it available to be played in real tarkov

**Comment by Billybishop** [comment]
It can be configured to be used with a live Escape From Tarkov build, but it is not recommended or supported. There are a couple important considerations to take note of:

- The project makes no effort to conceal the method of hooking or the cheat modules, so it is certainly detected for one or several reasons should you choose to configure it to hook a Live EFT instance - Refer to the ReadMe for details on how to configure it for a Live EFT installation.
- It has not been tested with the latest version that Live EFT is on, since the project focuses on only supporting the EFT builds that SPT-AKI works with, and testing it would definitely result in a detection/account ban.

That being said, if you're a developer looking to port the project into a surreptitious cheat that avoids BattleEye detection vectors then hooking NLog (which is how this project injects it's code) is probably one of the least desirable methods of hooking. If you're able to find a method of hooking that isn't outright detected by BE then you could most certainly bring over the cheat modules from this trainer, you will just need to ensure that whatever modifications any cheat modules make are not one of the BattleEye detection vectors. From what I've heard, BattleEye Anticheat works by hooking exception handlers and will periodically perform it's checks on the game's memory & code, rather than being an always-on module. These exception handlers get raised as normal, but BE inject's it's own cheat-detection code within an exception handler somewhere in the stack, perform's it's checks, then quietly cleans up after itself (making it hard to find). For this reason if you wish to locate or identify where BattleEye is checking then you should be ready for a long arduous process of trial and error with many banned accounts. Having to constantly find a new account to test with will be expensive over time.

There's also the rare possibility of getting your IP and machine HWID getting flagged by BE/BSG. I've only heard this happening to developers that tinker with the game though.

**Comment by brodiaga12** [comment]
Hello, can anybody help me with in-raid health regeneration?? i have spt aki local srver, i need mod or fing server setting for on this feature
