### ISSUE TITLE
An idea about "track"

### ISSUE THREAD

**Issue by mmnt1337** [sailro/EscapeFromTarkov-Trainer#107]
Hello, i have an idea about "track". When track shows us items, he signs them with numbers with "K", is that the price, right?
Is it possible to add the ability to filter items by price like in "tracks/sr" with rarity?
Is it also possible to track multiple items in one command? Ex: track kek, ledx, card;
Best regards :)

**Comment by LazySylaR** [comment]
Hello. Thank you very much for the trainer, all functions work. But I can't enable tracker functions. When I turn them on in the GUI, nothing changes in the game. I can't figure out what I'm doing wrong. Can you tell me what exactly and where to include, or can I write it in the ini? Or give me an ini file with the function enabled and working so that I can replace mine?

**Comment by sailro** [comment]
you have to user the `track <item>` command to add an item to the tracklist.

This way you can keep your tracklist and choose in the GUI to display tracked items or not. Have a look at the main readme. Everything is explained.
