### ISSUE TITLE
change tarkov installation

### ISSUE THREAD

**Issue by kenneth-knight** [sailro/EscapeFromTarkov-Trainer#110]
I have a local copy of Tarkov on my system. when I compile and try to run. it tries to put the files in my live tarkov version. how would I change it to run on my local copy of tarkov instead of my live version? thank you for this by the way.

**Comment by sailro** [comment]
Just to be sure: do you try to compile by yourself the solution using Visual Studio?

If yes then have a look at this:
https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/NLog.EFT.Trainer.csproj#L17

Because the dll is copied here (only the dll is copied, you have to handle other required files):
https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/NLog.EFT.Trainer.csproj#L165

If you are using the universal installer instead, just pass your full-path to the installer:
`installer.exe my\path\to\my\tarkov\copy`

**Comment by kenneth-knight** [comment]
sorry to keep bothering you. but when I try to open this project in Visual studio all the references are broken.

when I open a new C# project the references work and are good to go. but I cannot open this one because it will not find any references and will not get the path. any help would be greatly appreciated.

**Comment by sailro** [comment]
Same thing, adjust path here https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/NLog.EFT.Trainer.csproj#L19

Given it is used by all references.

**Comment by kenneth-knight** [comment]
AWESOME that worked for the NLOG, nut I noticed the installer is also having the reference issue. and I looked in the csproj for that and did not see anything pointing to any DLL area's. how would I fix that?

![image](https://user-images.githubusercontent.com/89554264/143310151-3a117ad7-9e2d-477b-bfc0-8d6e70e66294.png)

**Comment by sailro** [comment]
In this case it is another issue. You have to restore nuget packages (right-click on the project then Manage nuget packages).

You know, those are typical .NET dev setup issues. Trying to update the trainer will be another league of difficulty :)
