### ISSUE TITLE
Some tasks cannot be displayed

### ISSUE THREAD

**Issue by aierxiya** [sailro/EscapeFromTarkov-Trainer#231]
The quest for the forest and the quest for the bunker are not displayed properly

**Comment by sailro** [comment]
Could you elaborate a bit more, other quests are working?

**Comment by aierxiya** [comment]
All other tasks are normal, but the markers are not displayed properly in the bunker Part1 and the convoy task

**Comment by toxicspike** [comment]
Hi,
Not sure if this is still under investigation, but I've noticed a similar issue and would like to know if this intended:
On quests where you have to interact with something (place m2000, pick smth, stash smth, etc.) the quest marker shows where and what to do. On quests where the task is "locate" or "check" (i.e. The Bunker - Part 1; The Bunker - Part 2; Back Door; Inventory Check; The one where you have to find and a tank on reserve but not interact) it doesn't show a marker for me. I noticed similar on earlier quests as well, but never really thought about it till now.
If this is intended, could you expand your quest marker to show these things as well?
Sorry if this doesn't belong here, I figured the issue is the same so no need for an additional thread

**Comment by sailro** [comment]
Okay I see

**Comment by sailro** [comment]
We should be good now, I added a new kind of markers for places to visit. I also updated all quest markers so we can now display exact task and related quest name.

![image](https://user-images.githubusercontent.com/638167/212361140-09f94691-3fb3-43fa-80b6-16dfcad30a4e.png)

![image](https://user-images.githubusercontent.com/638167/212361221-c9631150-d3db-428b-b1b1-1340e6b418fd.png)
