### ISSUE TITLE
How does one actually compile this?

### ISSUE THREAD

**Issue by ValmiraOfficial** [sailro/EscapeFromTarkov-Trainer#261]
I have no idea what I'm doing with visual code, and I'm trying to utilize this in SPT-AKI 2.2.1 in Tarkov Vers. 0.12.12.15.16778

Your universal installer does not work with this version of tarkov because you did not allow for older versions of tarkov to work alongside it. Secondly, I saw on this site (link: https://www.unknowncheats.me/forum/escape-from-tarkov/465669-spt-aki-cheats.html ) That this would work with all versions. Also, like in this issue tag ( https://github.com/sailro/EscapeFromTarkov-Trainer/issues/248 ) please don't just insult me, Yes I know I'm not great at this and it may just be *super* easy to figure out, but at the same time your manual install is pretty vague. So please, don't insult those who don't understand. Thanks.

**Comment by sailro** [comment]
Hello,

Indeed, this is an old version of Tarkok, that is not directly supported.

The way it works with the universal installer, is that it should work with a lot of versions, but not when BSG is completely refactoring their APIs (they do that on a regular basis). That's why I keep branches for old versions but I cannot make sure it will work for every versions already released.

The best you can do:

- Given your version is `0.12.12.16778` and we have `0.12.12.16909`, `0.12.12.16584` as supported versions, you can try to instruct the installer to use one of them like this (do not forget the `dev-` prefix):

`Installer -b dev-0.12.12.16909`

- If it is still not working, the best you can do is to move to a recent Tarkov/spt-aki version.

**Comment by ValmiraOfficial** [comment]
a Manual install is preferred if possible as for some reason the universal isn't even locating it anymore despite being in the files *with it*, little confusing for me but eh.

My main question is how to compile it using Visual, as I don't know and I'm not finding much online relating to that subject.

![image](https://user-images.githubusercontent.com/72147599/203978168-1b3c72ae-a5b3-4802-a10d-d4000924ad13.png)
This is what the console throws, again I'd prefer to run with manual install *if possible* however if it isn't than I will attempt to find a way utilizing emutarkov as a possibility.

thanks for trying to guide me through this.
