### ISSUE TITLE
Client Crash Out of memory

### ISSUE THREAD

**Issue by dotOperator** [sailro/EscapeFromTarkov-Trainer#296]
SPT-AKI 3.4.1
Running amands graphics and system configurator mods
32GB ram
EXCEPTION: System.OutOfMemoryException: Out of memory
  at (wrapper managed-to-native) System.Object.__icall_wrapper_ves_icall_object_new_specific(intptr)
  at System.Linq.Lookup`2[TKey,TElement].GetGrouping (TKey key, System.Boolean create) [0x0006c] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at System.Linq.Lookup`2[TKey,TElement].Create (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0001f] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at System.Linq.GroupedEnumerable`2[TSource,TKey].GetEnumerator () [0x00000] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at EFT.Trainer.Features.PointOfInterests.ProcessDataOnGUI (EFT.Trainer.Features.PointOfInterest[] data) [0x00041] in <706fdd1d7645436d9104024db075c1e3>:0 
  at EFT.Trainer.Features.CachableFeature`1[T].OnGUIWhenEnabled () [0x00016] in <706fdd1d7645436d9104024db075c1e3>:0 
  at EFT.Trainer.Features.ToggleFeature.OnGUI () [0x00008] in <706fdd1d7645436d9104024db075c1e3>:0 
2023-02-12 12:41:59.373 -05:00|0.12.12.32.20765|Error|Default|OutOfMemoryException: Out of memory
System.Linq.Lookup`2[TKey,TElement].GetGrouping (TKey key, System.Boolean create) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Lookup`2[TKey,TElement].Create (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.GroupedEnumerable`2[TSource,TKey].GetEnumerator () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
EFT.Trainer.Features.PointOfInterests.ProcessDataOnGUI (EFT.Trainer.Features.PointOfInterest[] data) (at <706fdd1d7645436d9104024db075c1e3>:0)
EFT.Trainer.Features.CachableFeature`1[T].OnGUIWhenEnabled () (at <706fdd1d7645436d9104024db075c1e3>:0)
EFT.Trainer.Features.ToggleFeature.OnGUI () (at <706fdd1d7645436d9104024db075c1e3>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class296:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by dotOperator** [comment]
more clarification - client freezes then closes after about 13-20 minutes (interchange is pretty consistently 13-14 minutes)

**Comment by sayrex2009** [comment]
same problem. 10 - 15 minutes and crashes accompanied by freezes

**Comment by sayrex2009** [comment]
immediately after switching on. virtual memory starts to fill up. And as soon as it ends, the game crashes. It seems that the list is constantly filled, but not cleaned. And with all this, Loot does not work at all

**Comment by hughz001** [comment]
are you 2 using ISLC if not you should be and that should also fix this problem for you if you dont know what it is type into youtube there are many vids :) hope this helps

**Comment by Brostopeles** [comment]
Might be related to cache update causing stuttering on my machine (every cache update micro stutters). I'm wondering if this problem can be mitigated by making an option to update another way instead of time based like with a hotkey or when you turn the option on it only updates once. The stutter with the loot option seems to be worse the more items you have on the tracklist. Putting items on the wishlist instead ingame and using that as much as possible seems to have removed the stutter for that but the quest option causes a significant stutter when I have it on every update (even if there are no quests to track).

ISLC is working but it's not a solution as the program here has a memory leak that happily fills all your ram and ISLC has to purge about once an hour.

**Comment by solareon** [comment]
@Brostopeles have you tried since the loot refactor? It now runs based off cached GameState data rather than hitting the games internal methods for finding loot. I tried it on a 9900k and didn't notice any microstutters. There are some performance hits from the draw skeletons and wallhack functions as those can't rely on the GameState cache which in the default config is every 2 seconds. https://github.com/sailro/EscapeFromTarkov-Trainer/blob/d7fddbb5bb9cd3d528d1c59df8e53f7043c7a0ca/Features/GameState.cs#L20

**Comment by Brostopeles** [comment]
I do have the latest version installed from the installer but I have not tested the tracklist since, because I find that the wishlist is much more convenient. Oddly I do not feel any performance hits from using wallhack/radar/map/charms although I am also getting microstutters from wallshoot for some reason but that is a non issue as I just use a mod to add OP ammo.

**Comment by sailro** [comment]
@Brostopeles Microstutters from wallshoot are now fixed.

I had a deeper look and they just disable the Unity Garbage-Collector when in-raid (to prevent frame drops due to cleaning), if you have more than 12GB of RAM in your system....

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/51f8fcb0-f4bc-4873-af27-c4f6467813b5)

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/b43caa65-41fc-43b8-8c0c-7420b19e9107)

Even without us, the memory usage is growing, but the fact we do a lot of work if of course increasing the speed to which we come to be out of memory .

I tried to re-enable the Garbage Collector and I was able to keep the game at around 2.7 GB RAM usage.

The Unity version they use is compatible with incremental GC collection, so we should be able to do something smart.

I can either add a parameter to control the GC from the trainer, or monitor the memory and kick a memory cleaning when needed.
