### ISSUE TITLE
loadwl - Wishlist command

### ISSUE THREAD

**Issue by cptcl** [sailro/EscapeFromTarkov-Trainer#337]
First of all, let me say.... nice work on this whole thing.
When i start the game and alter my wishlist and then go in a raid and use the "loadwl" command.. it loads the "old" wishlist.
After raid i alter the wishlist again.. go in raid.. use "untrack *" command and all tracks disapear. 
Then using "loadwl" again and it loads the very first wishlist from since when i startet the game, plus what i added to it. but it dont untrack things i deleted from wishlist. So i can only add things but not delete?
Am i doing it wrong? or this a bug?

**Comment by sailro** [comment]
The `loadwl` command allows to load the tracklist from the tarkov wishlist. Only one small constraint for the moment, **it must be invoked in-raid or from the hideout so that the list is up-to-date in the player's profile**.

So indeed in a way it is a kind of bug, but it is what we have for now. I will try to have a deeper look to see if we can safely invoke it everywhere.

**Comment by cptcl** [comment]
Thanks for the fast reply. So just change things on wishlist,... than go raid,... do "untrack *" and after that.. "loadwl" right? and it should be up to date then

**Comment by sailro** [comment]
I found an indirect way that is working properly now

**Comment by cptcl** [comment]
> I found an indirect way that is working properly now

And how can i use that workaround?

**Comment by solareon** [comment]
@cptcl once the fix is merged then just run the installer and it'll work.

**Comment by sailro** [comment]
The fix is merged, you can update your installation re-running the installer @cptcl 

In the end, we removed the `loadwl` command. And we added an option to directly track the tarkov wishlist  in the `loot` options.

So no need to add/delete/go back and forth between the EFT wishlist and our tracklist:

![2023-03-17 19-44  (0)](https://user-images.githubusercontent.com/638167/225992173-b10167f5-acc6-48b3-af2c-261c56424f2d.png)

Exemple using the following commands in the console:
```
-- with loot/TrackWishlist disabled --
untrack *
track PS
track "gphone yellow"
-- enabling loot/TrackWishlist
tracklist
```
![2023-03-17 19-49  (0)](https://user-images.githubusercontent.com/638167/225993013-0b8f41b9-11bb-4e5f-bed5-f49ea233a7ba.png)
