### ISSUE TITLE
Cannot convert method while trying to fix the code 

### ISSUE THREAD

**Issue by ssscriptz** [sailro/EscapeFromTarkov-Trainer#34]
E:\EFT (Live)\EscapeFromTarkov-Trainer-e59d30caad6623c4253ca9b4f3d00dfd499a2534\Features\GameState.cs(50,16,50,28): error CS0428: Cannot convert method group 'IsYourPlayer' to non-delegate type 'bool'. Did you intend to invoke the method?

![ghju](https://user-images.githubusercontent.com/85771892/121759638-a2f92500-caf4-11eb-89c9-44824718fb97.PNG)

**Comment by sailro** [comment]
That's because you are trying to compile the `main` branch against an old EFT version.

Checking the history, EFT moved IsYourPlayer from a method call to a property with `0.12.10.11661`

See:
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/e6c544cfb309786e3cb3807e58c1058f1037233e#diff-c4e70dff0bd175666ed190f6e4bc420a4caf82a74e54f5ad01df4c71551ca8bb

So if you need to compile against an old version, used existing [branches](https://github.com/sailro/EscapeFromTarkov-Trainer/branches)
