### ISSUE TITLE
Support for version 0.13.1.24742.

### ISSUE THREAD

**Issue by zerosaboteur** [sailro/EscapeFromTarkov-Trainer#377]
Hi I just wanted to try your app, but I cannot install it for 0.13.1.24742. I receive error:
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/32568216/185cd5e4-db2b-4a4b-a471-f47cc3b505dd)

Is it planned to release new version with support for spt-aki Version 3.5.8?

**Comment by sailro** [comment]
That's because you are not using the trainer on a spt-aki EFT. See my screenshot below with a proper installation:

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/bc666bd6-d220-4b64-8366-7c98e5546442)

You are not using the proper EFT version. You need 0.13.0.23399 for spt-aki 3.5.8.
