### ISSUE TITLE
"Radar" and "Map" features are affecting the weather

### ISSUE THREAD

**Issue by MongMikng** [sailro/EscapeFromTarkov-Trainer#378]
It seems that the "Radar" and "Map" features are affecting the weather. I'm not sure exactly which feature is causing the problem. When using the trainer, the weather always stays clear. Another problem is that when I change the weather to rainy using a weather changing mod, and then use the "map" feature, it changes back to clear weather.

**Comment by sailro** [comment]
Indeed, for now we need to alter the Weather to correctly display the radar/map.

The call is here:
https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/Features/BaseMapToggleFeature.cs#L68

Because the "trick" is to reuse a similar player camera, but with a different angle/position, so if the weather is not clear, we are not able to display a crisp radar/map. We'll have limited viewing distance (fog etc).

**Comment by MongMikng** [comment]
Understood. Then, is there a way to keep the game's weather unaffected even if the radar is not crisp? If it's impossible, as cumbersome as it may be, I guess we'll have no choice but to manually change the weather using the weather change mode for each raid. 😆
