### ISSUE TITLE
 Problem with installation! (Installer.exe)

### ISSUE THREAD

**Issue by ByYasin** [sailro/EscapeFromTarkov-Trainer#45]
How exactly should Installer.exe be opened? Even if I open it with cmd as an administrator, it does not run. The game does not open even if I show the target folder? can you post a screenshoot for this tutorial or video?

**Comment by ByYasin** [comment]
Additionally, the version of AKI I play: 0.12.10.2.12893

**Comment by sailro** [comment]
The installer requires .NET Framework 4.7+ to run. It will install necessary files, it will not act as a loader for the game.

**Comment by FrostyasFloop** [comment]
I have the latest Net Framework, but I still can't get it to run properly. Is there a certain way to setup the installation? I'm not code savvy so use layman's terms.

**Comment by sailro** [comment]
I'm not sure to understand what is the exact problem, a lot of users are using this installer without any issue. Do you have screenshots or anything what could help?

Like what happens if you open a command prompt, and run the exe ? (do not run the exe directly, open a command prompt first).

My guess is : it is not able to find a EFT installation.

So you have to manually run like this:

`installer.exe "Path\To\Your\Eft\Installation"

But this is already covered in the documentation.

**Comment by FrostyasFloop** [comment]
I'm sorry, I might just be missing something. I'd send you screenshots, but there's nothing to show. The program starts up and immediately closes. I've made sure to run a CMD prompt as Admin first. I've even tried running it manually through the CMD, but it doesn't recognize the EXE. Is there anything I'm missing? Does the installer.exe have to be in a certain place on my computer or something? I just don't know.

**Comment by sailro** [comment]
No the executable is completely standalone. You can run it from any directory. Perhaps an issue with your antivirus software ? (But I never saw that previously).

**Comment by make-believe-agency** [comment]
Well my issue is running the `installer.exe "Path\To\Your\Eft\Installation"` as an spi-aki user is the latest master branch is pulled, which is incompatible with version 0.12.10.2.12893 which spi-aki needs.

Is there a way to tell installer.exe which branch to pull & compile, or create an installer.exe specific for spi-aki users?

**Comment by sailro** [comment]
Ok got it. We have support for `0.12.10.2.12893`, but changes I made for latest EFT introduced an issue with the installer. (after this it should try to compile with the `0.12.10.2.12893` branch, but stops given the file not found error is fatal).

**Comment by sailro** [comment]
I published a new version of the installer:

https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-1.1

@make-believe-agency could you try this one on your side to see if it fixes your issue?

Thanks

**Comment by make-believe-agency** [comment]
@sailro Yep that worked thanks! I noticed something else doing this, on my machine Installer.exe defaults to the live installation.

This happens when launching through powershell without passing a directory to it, as well as launching the .exe directly. So result in my environment is double clicking the file means I have to delete my EFT install and redownload.
![Screenshot 2021-07-12 165423](https://user-images.githubusercontent.com/66669966/125244593-d9fc6980-e332-11eb-85a1-06d6ec7aad0d.jpg)

When I give Installer.exe the path of sptarkov, it then works as intended. Perhaps a quick fix would be to force users to give Installer.exe the correct path, otherwise it won't run?
![Screenshot 2021-07-12 165602](https://user-images.githubusercontent.com/66669966/125244658-eda7d000-e332-11eb-8495-b10181f094ed.jpg)
