### ISSUE TITLE
An issue for 0.14.1

### ISSUE THREAD

**Issue by MRS88** [sailro/EscapeFromTarkov-Trainer#454]
Hello! As I see there isn't installer for the newest version?

![photo_2024-02-29_23-42-27](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/53020973/028f5f3f-cf41-49f8-87fa-8e9f2c8e1870)

**Comment by LeooM99** [comment]
Hello!! That's correct, since the "SPT-AKI 3.8.0 BleedingEdge" version doesn't support mods. It seems the "trainer" is considered a mod by the game. So unfortunately, if the SPT developers don't change that, it will be impossible to play with the "trainer". Only from version 0.13 of "Tarkov" will it be usable. Regards.

**Comment by sailro** [comment]
I think we should be fine, we are just waiting for 3.8.0 to be released, then we'll update what's needed
