### ISSUE TITLE
SPT 3.8.0

### ISSUE THREAD

**Issue by Kogzu** [sailro/EscapeFromTarkov-Trainer#468]
SPT 3.8.0 gonna be out in 10 hoursfrom now, spt dev says that latest BE and full release gonna have same files so for now

EFT version 0.14.1.29197

- [x] Faulting features: QuickThrow, NoRecoil, NoSway and Quests **[fixed]**

Wallhack: 

- [x] Some scavs get boss color propably because of new type of scav "scav assault" **[fixed]**

Aimbot: 

- [x] Silent aim very rarely shoot when you hipfire, when you scopein its shooting but dont redirect bullet to head **[fixed]**

- [x] Getting hit by own bullet using silent aim still occurs :) **[fixed]**

Loot:

- [X] I can confirm that issue #467 occurs **[fixed]**

Everything else sems to work fine

I hope its not to early and thank you for your work

**Comment by sailro** [comment]
https://github.com/sailro/EscapeFromTarkov-Trainer/pull/469

So it should compile properly now.

**Comment by sailro** [comment]
+ @LeooM99, could you give an example of what you are tracking for the #467 bug ?

**Comment by sailro** [comment]
@Kogzu I think I fixed the self damage issue but indeed the aimbot/silentaim is quite broken currently

**Comment by Kogzu** [comment]
> * @LeooM99, could you give an example of what you are tracking for the [TRACKING LOOT ISSUE AGAIN (SOLVED) #467](https://github.com/sailro/EscapeFromTarkov-Trainer/issues/467) bug ?

"track prs", "track gs" corspe dont have this ammo
![2024-04-03 15-01 _229 6, 8 6, -18 0_-0 1, 0 9, -0 4, -0 2_10 20 (0)](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/143875997/44a68645-a180-48bb-b4a9-7ce5238cdad7)

**Comment by sailro** [comment]
ok indeed I repro.

**Comment by LeooM99** [comment]
> * @LeooM99, could you give an example of what you are tracking for the [TRACKING LOOT ISSUE AGAIN (SOLVED) #467](https://github.com/sailro/EscapeFromTarkov-Trainer/issues/467) bug ?

Hi, I'm sorry but I haven't taken screenshots of the bug. Also, I've downgraded to Spetaki 376, and I'm not playing on 380 until it stabilizes as you had mentioned. I apologize for not being able to help. Like I mentioned, the bug was that every time I tracked bullets, whether it was M993, M61, or others, they all appeared in PMC or BEAR bodies, where they clearly weren't supposed to be. This happened with bullets of all calibers. However, as I mentioned earlier, I haven't taken screenshots of the bug.

**Comment by sailro** [comment]
I fixed the issue with loot tracking

**Comment by radcrazykid2** [comment]
Cant compile for 29351 :(

**Comment by radcrazykid2** [comment]
Target EscapeFromTarkov (0.14.1.29197) in G:\Games\backup.
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.14.1.29197 not found.
Unable to compile trainer for version 0.14.1.29197. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

please help?

**Comment by sailro** [comment]
enabling `nocoll` feature (No physical collisions, making you immune to bullets, grenades and barbed wires) seems to affect the aimbot issue.

- either it will properly shoot (no need to aim) but without targeting anything
- or it will work fully 

A [raycast ](https://github.com/sailro/EscapeFromTarkov-Trainer/blob/0270f4b0f3fdb123cd406d760227bf3e98c0c706/Extensions/CameraExtensions.cs#L19-L27) is used to detect whether something is visible at a position, and this raycast simply hits the player instead of the target when collisions are active. Aiming was just making this to work given the camera was a little further than the player body in this case.

So I have that to fix, and I still need to understand why we do not properly target the head everytime.

**Comment by Stonewall-RL** [comment]
**Is this issue the reason it fails to compile currently?**

**Comment by sailro** [comment]
> **Is this issue the reason it fails to compile currently?**

No, it compiles properly:

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/fb968f4e-8b93-4b55-b5a9-b76298e93849)

The reason is probably that you are trying to compile against an unsupported version. It is documented in the readme.

**Comment by sailro** [comment]
Fixed silentaim/aimbot here:
https://github.com/sailro/EscapeFromTarkov-Trainer/pull/473/files

**Comment by sailro** [comment]
Fixed colors here:
https://github.com/sailro/EscapeFromTarkov-Trainer/pull/474/files

We now have configurable colors for:
* Scav
* ScavRaider
* ScavAssault
* Boss
* Cultist
* Bear
* Usec
* Marksman
* RogueUsec
