### ISSUE TITLE
Feature question

### ISSUE THREAD

**Issue by Phioster** [sailro/EscapeFromTarkov-Trainer#477]
Is it possible to have the loot teleporter released on unknown cheats implemented or did you tried it and it didn't work?

**Comment by sailro** [comment]
Could you share a pointer on this?

**Comment by Phioster** [comment]
https://www.unknowncheats.me/forum/escape-from-tarkov/618542-loot-teleport-0-14-a.html

**Comment by sailro** [comment]
Yes I tried, it is a bit clunky, and the game can easily crash.

Instead of teleporting we can even spawn any item in our backpack. See the demo video below where I'm trying a new `spawn` feature. You need to finish the raid to really see the loot.

I'm creating 2x red keycards (5c1d0efb86f7744baf2e7b7b) and 2 GPUs (57347ca924597744596b4e71)
https://www.dropbox.com/scl/fi/urtn2idv1cs53rmjx24sw/tarkov.spawn.mp4?rlkey=y7m9un0fb9n2hyvndp1605tuz&dl=0

**Comment by Phioster** [comment]
Thanks for looking into this, thought so while reading the forum that it would crash alot. Nice that you got another way to get free loot in raid but is it maybe possible that these things are marked FIR?

**Comment by sailro** [comment]
I added the feature (now spawning the item in front of the player), and yes I was able to mark spawned items as "found in raid"

**Comment by Phioster** [comment]
Nice appreciate your work :D
